### ISSUE TITLE
[SpringWebObjectFactory] Injection return already created AtmosphereResource

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere-extensions#183]
[See this thread](https://groups.google.com/forum/#!topic/atmosphere-framework/fICmdjgOw_8). It seems the injection is broken as the same `AtmosphereResource` instance instead of a new one, which put the framework in limbo. Must find a way to return unique `AtmosphereResource` instance instead of a SINGLETON. Not sure the regression is coming from where.

**Comment by seamusmac** [comment]
@jfarcand 
Do we really need to create instances of AtmosphereResource via Spring. Can we not just add something like: 
if (classType.getName().equals(AtmosphereResource.class.getName()))
			return classToInstantiate.newInstance();

I'm not sure I see the use case for when we would want to inject AtmosphereResource, or inject anything into them? 
Injecting BroadCasterFactories, Handlers, ManagedServices definitely have use cases though!

Reason I ask is two fold:
1. Performance, when will these beans ever getting removed from the Spring App Context? memory will keep going up....
2. Also I am using JRebel in development and with this change, JRebel keeps refreshing the context because of new beans being added to the Spring AppContext, whenever a multiple clients connect

**Comment by jfarcand** [comment]
@seamusmac I think we can make it configurable via an excluded list. The reason is the community asked many times to be able to, at bare minimum, injects XXXFactory from Atmosphere using Spring. So :+1: to switch it off by default for `AtmosphereResource`. 

What do you think? If you have the cycle, do me another favor and send me a pull request :-)

**Comment by seamusmac** [comment]
@jfarcand Okay, I'm happy to make AtmosphereResourceinjection configurable and turn it off by default.

I will create a pull request shortly and we can go from there.

**Comment by jfarcand** [comment]
@seamusmac I've modified a little your patch to allow any injectable classes to be excluded. Let me know what you think.

**Comment by seamusmac** [comment]
@jfarcand I tested you most recent changes, and it is working well for me now. Thanks for your help on this one. 
I created a small PR which is just cleanup.
